// The mutation registry: each entry breaks exactly one mechanism the plugin depends on, names
// the file it edits and the suite that is supposed to catch it. A mutation that NO suite
// catches means the suite is not really guarding that behaviour.
//
// `from` may be a string (exact, unique anchor) or a RegExp (for anchors whose surrounding
// whitespace is generated). `file` is relative to the project root.
export const MUTATIONS = [
  {
    name: 'writer-rebind',
    file: 'lib/live-move.mjs',
    suite: 'test/livetest.mjs',
    breaks: 'the live writer is never retargeted, so later appends land in the old project key',
    from: 'writer.header = headerWithCwd(writer.header, newCwd)',
    to: 'void 0 /* MUTATION: writer not retargeted */',
  },
  {
    name: 'route-to-engine',
    file: 'lib/live-move.mjs',
    suite: 'test/livetest.mjs',
    breaks: 'running sessions are handed to the spawned engine, so the file move races the writer',
    from: 'liveIds.push(id)',
    to: 'void id /* MUTATION: running session left to the engine */',
  },
  {
    name: 'leave-old-dir',
    file: 'lib/live-move.mjs',
    suite: 'test/livetest.mjs',
    breaks: 'the emptied session directory is left under the old project key',
    from: 'removeIfEmpty(fromDir)\n  removeIfEmpty(dirname(fromDir))',
    to: 'void 0 /* MUTATION: old directories left behind */',
  },
  {
    name: 'plain-header-copy',
    file: 'lib/live-move.mjs',
    suite: 'test/livetest.mjs',
    breaks: 'the replacement header adopts this module realm\'s Object.prototype, which DSH rejects',
    from: '  const next = Object.create(prototype === undefined ? null : prototype)\n  Object.assign(next, source, { cwd })\n  return Object.freeze(next)',
    to: '  return Object.freeze(Object.assign({}, source, { cwd })) /* MUTATION: realm-losing copy */',
  },
  {
    name: 'note-markers-dropped',
    file: 'lib/live-move.mjs',
    suite: 'test/livetest.mjs',
    breaks: 'result notes lose their signal marker, so a handled warning reads like a failure',
    from: '  const notes = [...pre.notes]\n  const noteOk = (value) => notes.push(`${MARK.ok} ${value}`)',
    to: '  const notes = [...pre.notes]\n  const noteOk = (value) => notes.push(String(value)) /* MUTATION: marker dropped */',
  },
  {
    name: 'companions-left-behind',
    file: 'lib/live-move.mjs',
    suite: 'test/livetest.mjs',
    breaks: 'only the generation the live writer holds is moved, so the session id stays in two project directories',
    from: '  for (const name of companions) {\n    const movedCompanion = relocateSessionLog(join(fromDir, name), join(toDir, name), newCwd)\n    alsoMoved.push({ name, frameCount: movedCompanion.frameCount, bytes: movedCompanion.bytes })\n  }',
    to: '  void companions /* MUTATION: only the writer\'s generation is moved */',
  },
  {
    name: 'undo-session-header',
    file: 'lib/live-move.mjs',
    suite: 'test/livetest.mjs',
    breaks: 'a rolled-back live Session keeps pointing at the destination',
    from: '      session.header = headerWithCwd(session.header, relocation.previousCwd)',
    to: '      void 0 /* MUTATION: Session header left at the destination */',
  },
  {
    name: 'undo-writer-header',
    file: 'lib/live-move.mjs',
    suite: 'test/livetest.mjs',
    breaks: 'a rolled-back live writer keeps pointing at the destination',
    from: '    writer.header = headerWithCwd(writer.header, relocation.previousCwd)',
    to: '    void 0 /* MUTATION: writer header left at the destination */',
  },
  {
    name: 'report-not-written',
    file: 'lib/live-move.mjs',
    suite: 'test/livetest.mjs',
    breaks: 'the announced report path names a file that was never written',
    from: '    fs.writeFileSync(result.reportFile, JSON.stringify(result, null, 2))',
    to: '    void result /* MUTATION: report never written */',
  },
  {
    name: 'orphan-blocks-migration',
    file: 'lib/dsh-workspace-migrate.mjs',
    suite: 'test/selftest.mjs',
    breaks: 'an empty orphan session directory counts as a session, so it blocks an unrelated move',
    from: '        if (empty) {\n          emptyOrphans.push(dir)\n          continue\n        }',
    to: '        void empty /* MUTATION: empty orphans counted as sessions */',
  },
  {
    name: 'destination-claim-ignored',
    file: 'lib/dsh-workspace-migrate.mjs',
    suite: 'test/selftest.mjs',
    breaks: 'the plan re-points a record onto a path another record already claims, leaving DSH unable to boot',
    from: '    if (!samePath(from, to) && destinationClaims.length > 0) {',
    to: '    if (false && !samePath(from, to) && destinationClaims.length > 0) { /* MUTATION: destination claim ignored */',
  },
  {
    name: 'staged-guard-dropped',
    file: 'lib/dsh-workspace-migrate.mjs',
    suite: 'test/selftest.mjs',
    breaks: 'the staged apply/rollback scripts no longer check that DSH is stopped',
    from: '      ...(guarded ? [guard] : []),',
    to: '      ...(false ? [guard] : []), /* MUTATION: staged scripts lose the DSH guard */',
  },
  {
    name: 'origin-probe-never-listens',
    file: 'lib/dsh-workspace-migrate.mjs',
    suite: 'test/selftest.mjs',
    breaks: 'the recorded DSH origin is never reported as listening, so the guard falls back to the process probe alone',
    from: "  return { checked: true, listening: result.stdout.trim() === 'up', origin }",
    to: '  return { checked: true, listening: false, origin } /* MUTATION: origin never listens */',
  },
  {
    name: 'destination-content-allowed',
    file: 'lib/dsh-workspace-migrate.mjs',
    suite: 'test/selftest.mjs',
    breaks: 'a project move into a destination that is not empty is no longer a check failure',
    from: '  if (projectAction === \'move\' && destinationHasContent) {',
    to: '  if (false && projectAction === \'move\' && destinationHasContent) { /* MUTATION: content allowed */',
  },
  {
    name: 'engine-counts-files-only',
    file: 'lib/dsh-workspace-migrate.mjs',
    suite: 'test/selftest.mjs',
    breaks: '"is the destination empty?" goes back to counting FILES, so a destination holding only folders is merged into',
    from: '  const destinationEntries = newExists ? readEntries(to) : []',
    to: "  const destinationEntries = newExists && (newStat?.files ?? 0) > 0 ? [{ name: 'files-only', directory: false }] : [] /* MUTATION: folders do not count */",
  },
  {
    name: 'live-destination-content-allowed',
    file: 'lib/live-move.mjs',
    suite: 'test/livetest.mjs',
    breaks: 'the live precheck stops refusing a non-empty destination, so the move would merge two trees',
    from: '    if (project.destinationExists && project.destinationHasContent) {',
    to: '    if (false && project.destinationExists && project.destinationHasContent) { /* MUTATION: content allowed */',
  },
  {
    name: 'live-destination-entries-not-folders',
    file: 'lib/live-move.mjs',
    suite: 'test/livetest.mjs',
    breaks: 'the live precheck counts only files again, so a destination holding bare folders is accepted',
    from: '    destinationHasContent: typeof to === \'string\' && fs.existsSync(to) && !isEmptyDirectory(to),',
    to: '    destinationHasContent: typeof to === \'string\' && fs.existsSync(to) && fs.readdirSync(to).some((name) => fs.statSync(join(to, name)).isFile()), /* MUTATION: folders do not count */',
  },
  {
    name: 'live-refuses-empty-destination',
    file: 'lib/live-move.mjs',
    suite: 'test/livetest.mjs',
    breaks: 'an existing but empty destination is refused again, so the check passes and the move dies at the project layer',
    from: '    if (!isEmptyDirectory(to)) {',
    to: '    if (!isEmptyDirectory(to) || true) { /* MUTATION: any existing destination is refused */',
  },
  {
    name: 'manual-skips-check',
    file: 'client.js',
    suite: 'test/clienttest.mjs',
    breaks: 'the manual flow ignores a refused check and writes the plan anyway',
    from: '					if (verdict.ok !== true) {',
    to: '					if (false) { /* MUTATION: the manual flow ignores the check */',
  },
  {
    name: 'keep-does-not-create-destination',
    file: 'lib/live-move.mjs',
    suite: 'test/livetest.mjs',
    breaks: '「仅修改目录」stops creating a missing destination, so the registration has no directory to realpath',
    from: '  if (pre.project.createDestination === true && !fs.existsSync(pre.to)) {',
    to: '  if (false && pre.project.createDestination === true && !fs.existsSync(pre.to)) { /* MUTATION: never creates */',
  },
  {
    name: 'engine-keep-does-not-create-destination',
    file: 'lib/dsh-workspace-migrate.mjs',
    suite: 'test/selftest.mjs',
    breaks: 'the staged apply leaves a "keep" destination missing instead of creating it',
    from: '      if (!fs.existsSync(plan.to)) {\n        fs.mkdirSync(plan.to, { recursive: true })\n        created = true\n      }',
    to: '      if (false) { /* MUTATION: never creates the destination */\n        fs.mkdirSync(plan.to, { recursive: true })\n        created = true\n      }',
  },
  {
    name: 'state-reads-file-only',
    file: 'index.js',
    suite: 'test/hosttest.mjs',
    breaks: "the panel reads workspace.json instead of the live registry, so another plugin's change looks stale",
    from: "const [registry, runs] = await Promise.all([readWorkspaces(ctx), runEngine(['list', '--json'])])",
    to: "const [registry, runs] = await Promise.all([readWorkspaces(), runEngine(['list', '--json'])]) /* MUTATION: file only */",
  },
  {
    name: 'prune-ignores-usability',
    file: 'index.js',
    suite: 'test/hosttest.mjs',
    breaks: 'pruning deletes every staged run, including the ones that are still usable',
    from: 'const unusable = markRunUsability(runs, registry.workspaces).filter((run) => run.usable !== true)',
    to: 'const unusable = markRunUsability(runs, registry.workspaces).filter(() => true) /* MUTATION: deletes usable runs */',
  },
  {
    name: 'picker-not-preselected',
    file: 'client.js',
    suite: 'test/clienttest.mjs',
    breaks: 'the per-conversation entry stops preselecting the current workspace',
    from: /value: workspaces\.reduce\([\s\S]*?\n\t+\),/,
    to: 'value: "",',
  },
]
